package com.guappa.app.swarm

import android.util.Log
import com.guappa.app.agent.BusMessage
import com.guappa.app.agent.MessageBus
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import org.json.JSONArray
import org.json.JSONObject
import java.security.MessageDigest
import java.util.concurrent.ConcurrentHashMap

/**
 * Participates in holon deliberation councils in the World Wide Swarm.
 *
 * Holon lifecycle:
 * 1. Board Formation: receive invite, accept/decline
 * 2. Commit-Reveal: generate proposal, submit hash, then reveal
 * 3. Critique Phase: respond to adversarial critique
 * 4. IRV Voting: submit ranked-choice ballot
 * 5. Execution: execute assigned subtasks
 * 6. Synthesis & Dissolution: results combined, holon dissolved
 *
 * Commit-reveal prevents frontrunning: agents commit to a proposal hash
 * before seeing other proposals, then reveal the full text.
 */
class SwarmHolonParticipant(
    private val connector: SwarmConnectorClient,
    private val messageBus: MessageBus,
    private val identity: SwarmIdentity,
    private val reputationTracker: SwarmReputationTracker,
) {
    private val TAG = "SwarmHolonParticipant"
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    /** Active holons this agent is participating in. */
    private val activeHolons = ConcurrentHashMap<String, HolonState>()

    /** Proposals generated by this agent (stored locally for reveal phase). */
    private val pendingProposals = ConcurrentHashMap<String, String>()

    private val _holonStates = MutableStateFlow<Map<String, HolonState>>(emptyMap())
    val holonStates: StateFlow<Map<String, HolonState>> = _holonStates.asStateFlow()

    // --- Holon Lifecycle ---

    /**
     * Accept a holon invitation and join the deliberation board.
     */
    suspend fun joinHolon(holonId: String, taskDescription: String): Boolean {
        val peerId = identity.peerId ?: return false

        Log.d(TAG, "Joining holon: $holonId")

        val payload = JSONObject().apply {
            put("holon_id", holonId)
            put("peer_id", peerId)
            put("action", "accept")
        }

        val sent = connector.sendMessage(
            SwarmMessage(
                type = SwarmMessageType.HOLON_VOTE,
                fromPeerId = peerId,
                payload = payload,
            )
        )

        if (sent) {
            val state = HolonState(
                holonId = holonId,
                taskDescription = taskDescription,
                phase = HolonPhase.BOARD_FORMATION,
            )
            activeHolons[holonId] = state
            updateStatesFlow()
            reputationTracker.onHolonParticipation(holonId)
        }

        return sent
    }

    /**
     * Decline a holon invitation.
     */
    suspend fun declineHolon(holonId: String) {
        val peerId = identity.peerId ?: return

        val payload = JSONObject().apply {
            put("holon_id", holonId)
            put("peer_id", peerId)
            put("action", "decline")
        }

        connector.sendMessage(
            SwarmMessage(
                type = SwarmMessageType.HOLON_VOTE,
                fromPeerId = peerId,
                payload = payload,
            )
        )
    }

    /**
     * Generate a proposal for a holon's task using the agent LLM.
     * Returns the proposal text.
     */
    suspend fun generateProposal(holonId: String): String? {
        val state = activeHolons[holonId] ?: return null
        val sessionId = "holon_proposal_$holonId"

        Log.d(TAG, "Generating proposal for holon $holonId")

        val resultDeferred = CompletableDeferred<String>()

        val collectorJob = scope.launch {
            messageBus.messages.collect { message ->
                if (message is BusMessage.AgentMessage &&
                    message.sessionId == sessionId &&
                    message.isComplete
                ) {
                    resultDeferred.complete(message.text)
                }
            }
        }

        try {
            val prompt = buildProposalPrompt(state.taskDescription)

            messageBus.publish(
                BusMessage.UserMessage(
                    text = prompt,
                    sessionId = sessionId,
                )
            )

            val proposal = withTimeout(60_000) {
                resultDeferred.await()
            }

            // Store proposal for commit-reveal
            pendingProposals[holonId] = proposal

            // Update state
            activeHolons[holonId] = state.copy(
                phase = HolonPhase.COMMIT,
                myProposal = proposal,
            )
            updateStatesFlow()

            return proposal
        } catch (e: Exception) {
            Log.e(TAG, "Failed to generate proposal: ${e.message}")
            return null
        } finally {
            collectorJob.cancel()
        }
    }

    /**
     * Submit a sealed commitment (SHA-256 hash of proposal).
     * This must be done before seeing other proposals.
     */
    suspend fun submitCommit(holonId: String): String? {
        val proposal = pendingProposals[holonId] ?: run {
            Log.w(TAG, "No pending proposal for holon $holonId")
            return null
        }

        val hash = sha256Hex(proposal)
        val peerId = identity.peerId ?: return null

        Log.d(TAG, "Submitting commit for holon $holonId: ${hash.take(16)}...")

        val payload = JSONObject().apply {
            put("holon_id", holonId)
            put("hash", hash)
            put("peer_id", peerId)
        }

        val sent = connector.sendMessage(
            SwarmMessage(
                type = SwarmMessageType.HOLON_VOTE,
                fromPeerId = peerId,
                payload = JSONObject().apply {
                    put("action", "proposal_commit")
                    put("data", payload)
                },
            )
        )

        if (sent) {
            activeHolons[holonId] = activeHolons[holonId]?.copy(
                phase = HolonPhase.COMMIT,
                commitHash = hash,
            ) ?: return null
            updateStatesFlow()
        }

        return if (sent) hash else null
    }

    /**
     * Reveal the full proposal (after all agents have committed).
     */
    suspend fun submitReveal(holonId: String): Boolean {
        val proposal = pendingProposals[holonId] ?: return false
        val peerId = identity.peerId ?: return false

        Log.d(TAG, "Revealing proposal for holon $holonId")

        val payload = JSONObject().apply {
            put("holon_id", holonId)
            put("proposal", proposal)
            put("peer_id", peerId)
        }

        val sent = connector.sendMessage(
            SwarmMessage(
                type = SwarmMessageType.HOLON_VOTE,
                fromPeerId = peerId,
                payload = JSONObject().apply {
                    put("action", "proposal_reveal")
                    put("data", payload)
                },
            )
        )

        if (sent) {
            activeHolons[holonId] = activeHolons[holonId]?.copy(
                phase = HolonPhase.REVEAL,
            ) ?: return false
            updateStatesFlow()
            // Clean up stored proposal
            pendingProposals.remove(holonId)
        }

        return sent
    }

    /**
     * Submit a ranked-choice vote (Instant Runoff Voting).
     *
     * @param rankings Ordered list of proposal IDs, most preferred first.
     */
    suspend fun submitVote(holonId: String, rankings: List<String>): Boolean {
        val peerId = identity.peerId ?: return false

        Log.d(TAG, "Submitting IRV vote for holon $holonId: ${rankings.size} rankings")

        val payload = JSONObject().apply {
            put("holon_id", holonId)
            put("rankings", JSONArray(rankings))
            put("peer_id", peerId)
        }

        val sent = connector.sendMessage(
            SwarmMessage(
                type = SwarmMessageType.HOLON_VOTE,
                fromPeerId = peerId,
                payload = JSONObject().apply {
                    put("action", "vote")
                    put("data", payload)
                },
            )
        )

        if (sent) {
            activeHolons[holonId] = activeHolons[holonId]?.copy(
                phase = HolonPhase.VOTING,
                myVote = rankings,
            ) ?: return false
            updateStatesFlow()
        }

        return sent
    }

    /**
     * Perform local IRV tallying on a set of ballots.
     *
     * Instant Runoff Voting:
     * 1. Count first-choice votes
     * 2. If a candidate has >50%, they win
     * 3. Otherwise, eliminate the candidate with fewest votes
     * 4. Redistribute eliminated candidate's votes to next preference
     * 5. Repeat until a winner is found
     *
     * @param ballots Map of voter ID to ranked proposal IDs
     * @param weights Optional weights per criteria (feasibility, completeness, parallelism, risk)
     * @return Winning proposal ID, or null if no consensus
     */
    fun tallyIRV(
        ballots: Map<String, List<String>>,
        weights: Map<String, Double> = DEFAULT_IRV_WEIGHTS,
    ): String? {
        if (ballots.isEmpty()) return null

        // Collect all candidate IDs
        val allCandidates = ballots.values.flatten().toSet().toMutableSet()
        if (allCandidates.isEmpty()) return null

        // Working copy of ballots (we modify these as candidates are eliminated)
        val activeBallots = ballots.mapValues { it.value.toMutableList() }.toMutableMap()
        val eliminatedCandidates = mutableSetOf<String>()

        val totalVoters = activeBallots.size
        val majorityThreshold = totalVoters / 2.0

        for (round in 1..allCandidates.size) {
            // Count first-choice votes for remaining candidates
            val firstChoiceCounts = mutableMapOf<String, Int>()
            for (candidates in allCandidates) {
                if (candidates !in eliminatedCandidates) {
                    firstChoiceCounts[candidates] = 0
                }
            }

            for (ballot in activeBallots.values) {
                // Find first non-eliminated candidate
                val firstChoice = ballot.firstOrNull { it !in eliminatedCandidates }
                if (firstChoice != null) {
                    firstChoiceCounts[firstChoice] = (firstChoiceCounts[firstChoice] ?: 0) + 1
                }
            }

            // Check for majority winner
            val winner = firstChoiceCounts.entries.firstOrNull { it.value > majorityThreshold }
            if (winner != null) {
                Log.d(TAG, "IRV winner in round $round: ${winner.key} with ${winner.value} votes")
                return winner.key
            }

            // No majority: eliminate candidate with fewest votes
            val minVotes = firstChoiceCounts.values.minOrNull() ?: return null
            val toEliminate = firstChoiceCounts.entries
                .filter { it.value == minVotes }
                .map { it.key }

            // If all remaining candidates are tied, return the first one
            if (toEliminate.size == firstChoiceCounts.size) {
                return toEliminate.first()
            }

            // Eliminate (if tied for last, eliminate all tied)
            eliminatedCandidates.addAll(toEliminate)
            Log.d(TAG, "IRV round $round: eliminated $toEliminate")

            // Remove eliminated candidates from all ballots
            for (ballot in activeBallots.values) {
                ballot.removeAll(toEliminate.toSet())
            }

            // Check if only one candidate remains
            val remaining = allCandidates - eliminatedCandidates
            if (remaining.size == 1) {
                return remaining.first()
            }
            if (remaining.isEmpty()) {
                return null
            }
        }

        return null
    }

    // --- Holon event handling ---

    /**
     * Handle an incoming holon-related event from the swarm.
     */
    suspend fun handleHolonEvent(event: JSONObject) {
        val holonId = event.optString("holon_id", "") ?: return
        val action = event.optString("action", "")

        when (action) {
            "phase_change" -> {
                val newPhase = event.optString("phase", "")
                activeHolons[holonId]?.let { state ->
                    val phase = try {
                        HolonPhase.valueOf(newPhase.uppercase())
                    } catch (_: Exception) {
                        return
                    }
                    activeHolons[holonId] = state.copy(phase = phase)
                    updateStatesFlow()
                    Log.d(TAG, "Holon $holonId phase: $phase")
                }
            }
            "dissolved" -> {
                activeHolons.remove(holonId)
                pendingProposals.remove(holonId)
                updateStatesFlow()
                Log.d(TAG, "Holon $holonId dissolved")
            }
            "proposal_accepted" -> {
                reputationTracker.onProposalAccepted(holonId)
            }
        }
    }

    // --- Utility ---

    fun getActiveHolons(): Map<String, HolonState> = activeHolons.toMap()

    fun leaveHolon(holonId: String) {
        activeHolons.remove(holonId)
        pendingProposals.remove(holonId)
        updateStatesFlow()
    }

    fun shutdown() {
        activeHolons.clear()
        pendingProposals.clear()
        scope.cancel()
    }

    private fun updateStatesFlow() {
        _holonStates.value = activeHolons.toMap()
    }

    private fun buildProposalPrompt(taskDescription: String): String {
        return """
            You are participating in a swarm deliberation council (holon).
            Task: $taskDescription

            Generate a detailed execution plan. Your proposal will be evaluated on:
            - Feasibility (30% weight): Can this plan realistically be executed?
            - Completeness (30%): Does it cover all aspects of the task?
            - Parallelism potential (25%): Can subtasks run concurrently?
            - Risk mitigation (15%): Are failure modes addressed?

            Return a structured plan with:
            1. Summary of approach
            2. Subtasks with dependencies and estimated complexity (0.0-1.0)
            3. Risk assessment
            4. Expected outcome
        """.trimIndent()
    }

    companion object {
        val DEFAULT_IRV_WEIGHTS = mapOf(
            "feasibility" to 0.30,
            "completeness" to 0.30,
            "parallelism" to 0.25,
            "risk" to 0.15,
        )

        fun sha256Hex(input: String): String {
            return MessageDigest.getInstance("SHA-256")
                .digest(input.toByteArray(Charsets.UTF_8))
                .joinToString("") { "%02x".format(it) }
        }
    }
}

/**
 * State of a holon this agent is participating in.
 */
data class HolonState(
    val holonId: String,
    val taskDescription: String,
    val phase: HolonPhase = HolonPhase.BOARD_FORMATION,
    val myProposal: String? = null,
    val commitHash: String? = null,
    val myVote: List<String>? = null,
    val otherProposals: Map<String, String> = emptyMap(),
    val result: String? = null,
) {
    fun toJSON(): JSONObject = JSONObject().apply {
        put("holon_id", holonId)
        put("task_description", taskDescription)
        put("phase", phase.name)
        myProposal?.let { put("my_proposal", it) }
        commitHash?.let { put("commit_hash", it) }
        myVote?.let { put("my_vote", JSONArray(it)) }
        result?.let { put("result", it) }
    }
}

enum class HolonPhase {
    BOARD_FORMATION,
    COMMIT,
    REVEAL,
    CRITIQUE,
    VOTING,
    EXECUTION,
    SYNTHESIS,
    DISSOLVED,
}
